### ISSUE TITLE
Doors seem to break on MP with Biome Makeover installed

### ISSUE THREAD

**Issue by purejosh** [sketchmacaw/MacawsModsIssues#211]
**Describe the bug**
When Biome Makeover is installed on Fabric server 1.18.2, doors from MCW doors seems to break. They don't accept redstone input and the models don't update visually. 

**Mod name & Minecraft Version and Modloader**
Minecraft 1.18.2 with Fabric Loader 0.14.8
biomemakeover-FABRIC-1.18.2-1.4.28
mcw-doors-1.0.6fabric-mc1.18.2

**To Reproduce**
1. Install MCW Doors with Biome Makeover
2. Put pressure plates in front of any sliding door like the Shoji Doors. 
3. Try to use the doors with the pressure plates. 
4. Observe that the door doesn't open, and the model breaks if you try to close it while inputting redstone. 

**Additional context**
It could be other mods causing this... but I'm able to break, and subsequently fix, the issue when Biome Makeover is installed and removed.

**Comment by purejosh** [comment]
[latest.log](https://github.com/sketchmacaw/MacawsModsIssues/files/9182117/latest.3.log)

**Comment by purejosh** [comment]
https://user-images.githubusercontent.com/70633949/180805094-310ce184-ba33-48f2-bbd2-bc0e014c6958.mp4

**Comment by sketchmacaw** [comment]
Do you have a good connection on that server?

**Comment by purejosh** [comment]
I host the server, so yes. Sub 1ms.

**Comment by purejosh** [comment]
It's absolutely caused by certain mods, or having too many mods. Adding a mod that breaks it is reversible when I remove the mod. So it has nothing to do with connections, it's something internal that's breaking the model. 

Also, sounds stop working on the door, too. Note that I've only found this on the sliding doors. I haven't tested this on a swinging door.

**Comment by sketchmacaw** [comment]
Could you test the barn door and some normal door from it which acts the classic way?

**Comment by purejosh** [comment]
I can do that when I have my modded server up to 1.19.1

**Comment by sketchmacaw** [comment]
Should be fixed in the upcoming 1.0.7 update

**Comment by Chribit** [comment]
It is not fixed...

same setup as above, just 1.19.2 and using a swinging door (oak barn door).
normal door acts the classic way.

I'm using 1.0.8 of your doors mod

**Comment by purejosh** [comment]
I agree. I'm still having unusual separations from blockstate in client and blockstate in server. As if right clicking the block updates it to the client. 

Additionally, if another player places a block (door, fence) from your mod suite, other players don't always see the new block state, and are unable to move through that open door or fence until they interact with it, which updates the blockstate to the client. 

Macaw's mods are the only ones having these issues.

**Comment by Eatham532** [comment]
Hmm interesting. I have biome makeover installed and almost all of macaws mods as well (Everything but paintings.) Do not have this issue. Are you on forge? Because I am on fabric.

**Comment by Chribit** [comment]
I‘m on fabric as well. You can find my modlist on the discord in my other water-/lava-logged walls issue 😅
